on:
  push:
    tags:
      - '*'
jobs:
  test-tags:
    name: Test tags
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
 
      - name: Running on a tag branch.
        if: steps.branch-names.outputs.is_tag == 'true'
        run: |
          echo "Running on: ${{ steps.branch-names.outputs.tag }}"
          echo "Current branch: ${{ steps.branch-names.outputs.current_branch }}"
